spring:
#  datasource:
#    jndi-name: false
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:dgc;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
#    username: sa
#    password: ''
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/dgc
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    jndi-name: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

