server:
  port: 8090
spring:
  profiles:
    group:
      "dev": "h2"
  application:
    name: eu-digital-green-certificates-gateway
#  datasource:
#    jndi-name: jdbc/dgc
  datasource:
    url: jdbc:mysql://localhost:3306/dgc
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    jndi-name: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.xml
  task:
    scheduling:
      pool:
        size: 5
management:
  endpoints:
    web:
      exposure:
        exclude: "*"
  server:
    port: -1
dgc:
  jrc:
    url: https://covid-19-diagnostics.jrc.ec.europa.eu/devices/hsc-common-recognition-rat
    proxy:
      host: ${https.proxyHost:}
      port: ${https.proxyPort:-1}
      username: ${https.proxyUser:}
      password: ${https.proxyPassword:}
  validationRuleSchema: classpath:validation-rule.schema.json
  trustAnchor:
    keyStorePath: certs/ta.jks
    keyStorePass: dgcg-p4ssw0rd
    certificateAlias: dgcg_trust_anchor
  cert-auth:
    header-fields:
      thumbprint: X-SSL-Client-SHA256
      distinguished-name: X-SSL-Client-DN
springdoc:
  api-docs:
    enabled: false
