name: ci-master
on:
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: 'dgc-github'
        server-username: GITHUB_USER
        server-password: GITHUB_PAT
    - name: environment
      run: |
        sudo apt-get install --yes --no-install-recommends libxml-xpath-perl
        export VERSION=$(xpath -q -e "/project/version/text()" pom.xml)
        export VERSION=${VERSION//-SNAPSHOT}-$(git rev-parse --short ${GITHUB_SHA})
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo ${GITHUB_SHA} > github_sha256
    - name: Download Dependencies
      run: mvn dependency:go-offline
      env:
        GITHUB_USER: ${{ secrets.GPR_USER }}
        GITHUB_PAT: ${{ secrets.GPR_PAT }}
    - name: Set Version
      run: mvn -o --batch-mode versions:set -DgenerateBackupPoms=false -DnewVersion=${VERSION}
    - name: Deploy
      run: mvn -o --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Sonar
      run: |
        mvn -o --batch-mode verify sonar:sonar \
        -Dsonar.login=${SONAR_TOKEN} \
        -Dsonar.host.url=${SONAR_URL} \
        -Dsonar.organization=${GITHUB_REPOSITORY_OWNER} \
        -Dsonar.projectKey=${GITHUB_REPOSITORY/\//_}
      env:
        SONAR_URL: https://sonarcloud.io
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: DGCG001_TST
        path: /home/runner/work/eu-digital-green-certificates/dgc-gateway/target/DGCG001_TST*
    - uses: actions/upload-artifact@v2
      with:
        name: DGCG001_ACC
        path: /home/runner/work/eu-digital-green-certificates/dgc-gateway/target/DGCG001_ACC*
    - uses: actions/upload-artifact@v2
      with:
        name: DGCG001_PRD
        path: /home/runner/work/eu-digital-green-certificates/dgc-gateway/target/DGCG001_PRD*
    - name: mvn clean install -P docker
      run: mvn clean install -P docker
    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Build docker image
      run: docker build target/docker --file target/docker/Dockerfile --tag docker.pkg.github.com/${{ github.repository }}/backend:latest
    - name: Push docker image
      run: docker push docker.pkg.github.com/${{ github.repository }}/backend:latest
